name: "Generate Ensemble"
on:
  workflow_dispatch:
  schedule:
    - cron: "15 11,23 * * 2,3"


jobs:
  ensemble:
  # if: github.repository_owner == 'european-modelling-hubs'
    runs-on: ubuntu-latest

    steps:
    # checkout repo
    - uses: actions/checkout@v3


    - uses: r-lib/actions/setup-r@v2
      with:
        install-r: false
        use-public-rspm: true

    - name: Install HubValidations
      run: |
        install.packages("remotes")
        remotes::install_github("Infectious-Disease-Modeling-Hubs/hubValidations")
        
      shell: Rscript {0}

    - name: Generate Ensamble
      run: |
        # code here
      shell: Rscript {0}
